version: "3.9"

services:
  # --- SERVICIO DE BASE DE DATOS POSTGRES ---
  postgres:
    image: postgres:18
    container_name: postgres_comercio
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: comercio
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  # --- SERVICIO DE NESTJS ---
  nestjs:
    build: .
    container_name: nest_comercio
    command: npm run start:dev
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app

volumes:
  postgres_data:
